### PR TITLE
Update Restartbutton

### PR DESCRIPTION
**Pull request by Bluscream**
+ Now using https://github.com/MistressPlague/ChilloutButtonAPI
+ Added MelonPrefs for keybind + vr failsave
+ works in vr

### CODE REVIEW

**Comment by Bluscream** [comment]
Compiled version; [RestartButton.zip](https://github.com/aniiiiiimal/CVRMods/files/9410641/RestartButton.zip)
 requires https://github.com/MistressPlague/ChilloutButtonAPI/releases

**Comment by nyakowint** [comment]
lgtm, i think you might have to encase the path in extra quotes in the case of directories with spaces (windows moment)

**Comment by Bluscream** [comment]
You'll find a few more changes in the main branch of my fork now https://github.com/Bluscream-CVRMods/CVRMods

**Comment by nyakowint** [comment]
aight

**Pull request merged**
